PUGX/badge-poser

- README.md
Fixes a few grammar and spelling issues in the README.
For example, there is an awkward comma in the opening sentence.  Both "Packagist.org" and "packagist.org" were used.  One or the other should be used for consistency.
Use present tense in why to use a composer badge.  There was a run-on sentence in the "Contribution" section.
Other than that the changes are just the addition or removal of commas and the like.
> Fix a few spelling and grammar issues in the README.

- config/routes.yaml
- config/routes/badge.yaml
- config/routes/badge_redirect.yaml
- src/Controller/HomeController.php
- tests/Controller/Badge/ComposerLockControllerTest.php
- tests/Controller/Badge/DownloadsControllerTest.php
- tests/Controller/Badge/GitAttributesBadgeControllerTest.php
- tests/Controller/Badge/LicenseControllerTest.php
- tests/Controller/Badge/VersionControllerTest.php
I added the redirect routes for the badge routes in png.
I created a specific file for badge and redirect route.
I edited the config badge route for work with .svg extension and without .svg extension.
I removed a duplicate configuration for the homepage route.
I added a tests!
https://trello.com/c/Ep4OZDoy/25-no-backwards-compatibility-per-gli-alias-e-rotte-vecchie
> Add redirect and alias for badge routes

- README.md
- docker/dev/php-fpm/Dockerfile
- docker/dev/php-fpm/php-no-xdebug.sh
Running php-cs-fixer with xdebug disabled greatly improves running time. 
To do this, rebuild docker-compose `docker-compose up --build -d`!
> Run php-cs-fixer disabling xdebug

- docker/dev/php-fpm/Dockerfile
- docker/dev/php-fpm/composer-install.sh
The current composer install in the Dockerfile has hard coded the hash. This changes every time composer updates.
Instead, I've updated to make it use the programmatic install which downloads the hash on the fly.
https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
> Update composer install to use programmatic install 

- docker-compose.yml
Latest node image (10.12.0) is incompatible with upath@1.0.2 dep - lock to node 8 image until it's updated
Looks like upath@1.0.5 fixes it so probably not a hard one.
Error message:
error upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.12.0"
> Lock node image to 8

- .gitignore
- README.md
- composer.json
- composer.lock
- symfony.lock
This PR adds the brainmaestro/composer-git-hooks package and installs a pre-commit git hook to run phpunit, php-cs-fixer and phpstan. closes #270
> add git hook to run phpunit, php-cs-fixer and phpstan

- composer.lock
- symfony.lock
[v3/feat-upgrade-other-dependecies 29f1d13] feat: upgrade other dependencies
```
- Removing zendframework/zend-diactoros (2.2.1)
- Removing ramsey/uuid (3.9.2)
- Removing php-http/curl-client (v1.7.1)
- Updating ocramius/package-versions (1.4.2 => 1.5.1): Loading from cache
- Installing symfony/polyfill-uuid (v1.14.0): Loading from cache
- Updating php-http/discovery (1.7.0 => 1.7.4): Loading from cache
- Updating sentry/sentry (2.2.6 => 2.3.2): Loading from cache
- Updating sentry/sdk (2.0.4 => 2.1.0)
- Updating sentry/sentry-symfony (3.2.1 => 3.4.3): Loading from cache
- Updating composer/semver (1.5.0 => 1.5.1): Loading from cache
- Updating composer/xdebug-handler (1.4.0 => 1.4.1): Loading from cache
- Updating php-http/cache-plugin (1.6.0 => 1.7.0): Loading from cache
- Updating …
```
> feat: upgrade other dependencies

- src/Stats/Persister/RedisPersister.php
This is a hotfix for wrong call to `zadd()` method in Redis
> fix call to zadd method

- docker/dev/php-fpm/Dockerfile
This small modification will create a home for Composer, so that it can cache stuff; that cache in turn is leveraged by Prestissimo/Flex to improve downloads.
> Add Composer home dir

- tests/Contributors/Service/RepositoryTest.php
While trying to contribute, I got strange test failures. This was due to `https://helloacm.com/api/can-visit/?url=https://github.com/liuggio` responding 500. This fixes it, calling the GitHub page directly.
It's a dirty fix, but at least it works. How can we improve this?
> Fix test that uses external dependency

- composer.lock
- symfony.lock
- yarn.lock
[feat/upgrade-dependecies 26aef6e] feat(bump): upgrade dependencies
**Composer**
```
Package operations: 2 installs, 66 updates, 0 removals
- Updating composer/package-versions-deprecated (1.8.0 => 1.10.99): Loading from cache
- Updating symfony/flex (v1.7.0 => v1.9.1): Loading from cache
- Updating symfony/service-contracts (v2.0.1 => v2.1.3): Loading from cache
- Updating symfony/polyfill-mbstring (v1.17.0 => v1.18.0): Loading from cache
- Installing symfony/polyfill-php80 (v1.18.0): Loading from cache
- Updating symfony/console (v4.4.8 => v4.4.11): Loading from cache
- Updating badges/poser (v1.3.0 => v1.4.1): Loading from cache
- Updating php-http/discovery (1.7.4 => 1.9.1): Loading from cache
- Updating php-http/multipart-stream-builder (1.1.0 => 1.1.2): Loading from cache
- Updating …
```
> feat(bump): upgrade dependencies

- docker-compose.yml
- docker/dev/nginx/nginx.conf
This partially reverts some changes done in c21ed42dca2bf9d1f706ede5c2de69b4b1feada2, that prevented local dev env from properly run nginx and fpm
> re-enable proper nginx conf for dev

- .env.dist
- phpunit.xml.dist
This fixes PHPUnit execution on local docker images.
Is worth to notice that, in order to have a green build, you need to run build all the assets (I've noticed that `yarn` is not installed inside php-fpm container, is that intended?)
> Fixed local tests

- .circleci/config.yml
- composer.json
- composer.lock
- src/Controller/PackagistController.php
- tests/Controller/PackagistControllerTest.php
packagist-api [released a new version](https://github.com/KnpLabs/packagist-api/releases): now we can limit the amount of extracted results directly in packagist, instead of retrieving them all and doing limit on our side.
This should add further optimization to our autocompleted search.
> exploit limit in packagist api

- symfony.lock
- yarn.lock
[fix/upgrade-node-sass 979d687] fix: upgrade node-sass
fix this: https://github.com/PUGX/badge-poser/security/dependabot/yarn.lock/y18n/open
> fix: upgrade node-sass

- assets/styles/_input.scss
- assets/styles/app.scss
- templates/home/index.html.twig
[fix/ux-mobile 20e2a61] fix: ux mobile
closes #559
Before:
https://user-images.githubusercontent.com/190820/120112113-cd51f680-c174-11eb-9b88-748af0600f89.mp4
After:
https://user-images.githubusercontent.com/190820/120112119-d347d780-c174-11eb-80f3-70679394b4c3.mp4
> fix: ux mobile

- config/routes/badge.yaml
- config/services.yaml
- src/Badge/Model/Package.php
- src/Badge/Model/UseCase/CreateRequireBadge.php
- src/Controller/Badge/RequireController.php
- tests/Badge/Model/UseCase/CreateRequireBadgeTest.php
- tests/Controller/Badge/RequireControllerTest.php
closes #607
WDYT?
The new badge works with all requires, example:
```
/phpunit/phpunit/require/php
/phpunit/phpunit/require/ext-gd
/phpunit/phpunit/require/badges/poser
```
> feat: add badge php version require

- composer.json
- composer.lock
- src/Badge/Model/Package.php
[feat/bump-knplabs-packagist-api bf95fe2] feat: bump knplabs packagist-api to 2.x
The new version of package use the new API version of packagist: https://github.com/KnpLabs/packagist-api/pull/72
> feat: bump knplabs packagist-api to 2.x

- sys/cloudformation/stack.yaml
- sys/nginx/default.conf.template
- sys/nginx/lua/hook.lua
I don't know why but from today I receive the following errors in dev environment that did 500.
I comment the lines in diff and now work!
@fabiocicerchia PTAL
```
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/composerlock HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" CACHE[GET@@poser.local@@/phpunit/phpunit/composerlock]:1:-
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/d/daily HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" …
```
> fix: stop check canary

- .github/workflows/build.yml
- composer.json
- composer.lock
- config/packages/dev/routing.yaml
- config/packages/prod/routing.yaml
- config/packages/routing.yaml
- config/packages/test/framework.yaml
- config/packages/test/routing.yaml
- config/routes.yaml
- symfony.lock
```
Lock file operations: 0 installs, 53 updates, 0 removals
- Upgrading bitbucket/client (v3.3.1 => v4.2.0)
- Upgrading cache/adapter-common (1.2.0 => 1.3.0)
- Upgrading cache/hierarchical-cache (1.1.0 => 1.2.0)
- Upgrading cache/predis-adapter (1.1.0 => 1.2.0)
- Upgrading composer/pcre (1.0.0 => 1.0.1)
- Upgrading knplabs/github-api (v3.4.0 => v3.5.0)
- Upgrading php-http/cache-plugin (1.7.4 => 1.7.5)
- Upgrading phpstan/phpstan (1.4.0 => 1.4.2)
- Upgrading phpstan/phpstan-symfony (1.1.1 => 1.1.2)
- Upgrading phpunit/phpunit (9.5.11 => 9.5.13)
- Upgrading psr/cache (1.0.1 => 2.0.0)
- Upgrading psr/container (1.1.2 => 2.0.2)
- Upgrading psr/log (1.1.4 => 3.0.0)
- Upgrading sentry/sentry (3.3.5 => 3.3.7)
- Upgrading snc/redis-bundle (3.6.0 => 4.1.3)
- Upgrading symfony/asset (v5.4.0 => …
```
> feat: bump symfony v6

- composer.lock
```
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading knplabs/packagist-api (dev-master cf3906e => dev-master b7d41cc)
```
closes #738
> fix: description can be empty

- config/services.yaml
- src/Dictionary/AllInBadges.php
- src/Dictionary/Badges.php
- src/Service/SnippetGenerator.php
- tests/Dictionary/AllInBadgesTest.php
- tests/Dictionary/BadgesTest.php
- tests/Service/SnippetGeneratorTest.php
In this PR I removed from the services file badges arrays and I added two classes to store information.
I would like to discuss:
- the right position of those files
- the correct name for those files, I used the same name used before but I would like to improve them
> Added dictionary classes for badges removing them from services declaration

- README.md
It was annoying to see the PHP Logo as missing 😉 
Regards.
> Fixed PHP Logo in the ReadMe.md

- CONTRIBUTING.md
- Makefile
- assets/styles/app.scss
- sys/README.md
- templates/home/index.html.twig
Before:
After:
I change also `docker-compose` with `docker compose` as new standard! ;)
> fix: github ribbons forkme
