- src/PUGX/BadgeBundle/Controller/Badge/KernelExceptionListener.php
@leopro could you please check? thanks :P
> small KernelExceptionListener refactor and cleanup

- src/Badge/src/Model/UseCase/CreateComposerLockBadge.php
- src/Badge/tests/Model/UseCase/CreateComposerLockBadgeTest.php
> Fixes un-/committed spelling

- README.md
> Remove Pledgie badge

- config/services.yaml
- src/Service/CachedClient.php
https://trello.com/c/kn3JoDmA/32-servizio-cachedclient
> created cacedClient

- .circleci/config.yml
See https://trello.com/c/0z0qsjS7
> add circleCI conf

- .env.dist
- composer.json
- composer.lock
- config/packages/github_api.yaml
- config/services.yaml
- config/services_test.yaml
- phpunit.xml.dist
- src/Badge/Model/UseCase/CreateComposerLockBadge.php
- src/Contributors/Command/UpdateCommand.php
- src/Contributors/Model/Contributor.php
- src/Contributors/Service/Repository.php
- src/Contributors/Service/RepositoryInterface.php
- src/Controller/HomeController.php
- tests/Badge/Model/ParseStabilityTest.php
- tests/Badge/Model/UseCase/CreateComposerLockBadgeTest.php
- tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php
- tests/Badge/Model/UseCase/CreateLicenseBadgeTest.php
- tests/Badge/Model/UseCase/CreateVersionBadgeTest.php
- tests/Badge/Service/TextNormalizerTest.php
- tests/Contributors/Command/UpdateCommandTest.php
- tests/Contributors/Model/ContributorTest.php
- tests/Contributors/Service/RepositoryTest.php
https://trello.com/c/PnhrzSBA/12-rifattorizziamo-lo-script-python-per-estrarre-i-contributors-con-un-command-di-symfony
> Add business logic for fetch and cache contributors

- src/Badge/Model/UseCase/BaseCreatePackagistImage.php
- src/Badge/Model/UseCase/CreateComposerLockBadge.php
- src/Badge/Model/UseCase/CreateGitAttributesBadge.php
- src/Badge/Model/UseCase/CreateVersionBadge.php
- tests/Badge/Model/UseCase/CreateComposerLockBadgeTest.php
- tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php
- tests/Badge/Model/UseCase/CreateLicenseBadgeTest.php
- tests/Badge/Model/UseCase/CreateVersionBadgeTest.php
Add to v3 the PR: https://github.com/PUGX/badge-poser/pull/164
> Default badge on error.

- config/bundles.php
- config/packages/prod/sentry.yaml
- config/packages/sentry.yaml
> Enable sentry only prod environment

- config/routes.yaml
- src/Controller/PackagistController.php
- tests/Controller/PackagistControllerTest.php
https://trello.com/c/41Qis3Mw/26-searchpackagistcontroller
> Add controller to serach package by packagist.

- .gitignore
- .php_cs
- README.md
- composer.json
- composer.lock
- symfony.lock
I didn't include fixes.
Here is a preview, let me know:
```
1) src/EventListener/BadgeSubscriber.php (phpdoc_no_package, phpdoc_summary, yoda_style, binary_operator_spaces, phpdoc_separation, ordered_imports)
2) src/EventListener/StatsSubscriber.php (no_unneeded_control_parentheses, phpdoc_no_package, yoda_style, binary_operator_spaces)
3) src/Kernel.php (void_return)
4) src/Service/SnippetGeneratorInterface.php (phpdoc_no_package, phpdoc_summary)
5) src/Service/SnippetGenerator.php (phpdoc_no_package, phpdoc_summary, phpdoc_var_without_name, trailing_comma_in_multiline_array, binary_operator_spaces, phpdoc_separation, phpdoc_align)
6) src/Service/CachedClient.php (phpdoc_no_package, phpdoc_summary, single_quote, binary_operator_spaces)
7) src/Stats/Reader/ReaderInterface.php …
```
> add php-cs-fixer

- .env.dist
- config/routes.yaml
- config/routes/badge.yaml
- config/services.yaml
- phpunit.xml.dist
- src/Badge/Model/UseCase/CreateCircleCiBadge.php
- src/Controller/Badge/CircleCiController.php
- src/Service/CircleCiClient.php
- src/Service/CircleCiClientInterface.php
- tests/Badge/Model/UseCase/CreateCircleCiBadgeTest.php
- tests/Controller/Badge/CircleCiControllerTest.php
- tests/Service/CircleCiClientTest.php
Added new badge for circleCI! 🚀
> Feat - CircleCI badge

- config/routes.yaml
- config/services.yaml
- src/Controller/HomeController.php
- src/Stats/Reader/RedisReader.php
- templates/home/index.html.twig
- tests/Controller/HomeControllerTest.php
ok guys now only the layout is missing! @elfo404 where are you? :P
> Add logic for homepage and show action.

- templates/home/index.html.twig
> Add thanks to sentry in the footer.

- composer.json
See https://github.com/symfony/skeleton/issues/24
> move flex to dev requirements.

- config/routes/badge.yaml
> re-add deleted GET requirements

- README.md
I spent some time working on the v2 code before realising v3 was a thing (https://github.com/PUGX/badge-poser/pull/187#issuecomment-379476265). 
I've just added a warning to master about it.
> Add warning to v2 readme about v3 contributions

- docker/dev/php-fpm/Dockerfile
[v3/install-prestissimo 4a9eabf] Install prestissimo on container after composer
> Install prestissimo on container after composer

- composer.lock
[v3/bump-minor-version-of-symfony f2c71d4] Bump minor version of symfony
> Bump minor version of symfony

- assets/css/_input.scss
- assets/js/app.js
Adds a nice and simple spinner to the autocomplete text field while fetching results.
> Adds a spinner on the autocomplete while waiting for results

- assets/css/app.scss
- assets/js/app.js
> Adds an overlay and a spinner over the info box while fetching data

- composer.lock
- package.json
- src/Badge/Model/Package.php
- src/Badge/Model/UseCase/BaseCreatePackagistImage.php
- src/Badge/Model/UseCase/CreateCircleCiBadge.php
- src/Badge/Model/UseCase/CreateComposerLockBadge.php
- src/Badge/Model/UseCase/CreateDependentsBadge.php
- src/Badge/Model/UseCase/CreateDownloadsBadge.php
- src/Badge/Model/UseCase/CreateGitAttributesBadge.php
- src/Badge/Model/UseCase/CreateLicenseBadge.php
- src/Badge/Model/UseCase/CreateSuggestersBadge.php
- src/Badge/Model/UseCase/CreateVersionBadge.php
- src/Contributors/Service/Repository.php
- src/Controller/Badge/CircleCiController.php
- src/Controller/Badge/ComposerLockController.php
- src/Service/SnippetGenerator.php
- tests/Badge/Model/UseCase/CreateCircleCiBadgeTest.php
- tests/Badge/Model/UseCase/CreateComposerLockBadgeTest.php
- tests/Badge/Model/UseCase/CreateDependentsBadgeTest.php
- tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php
- tests/Badge/Model/UseCase/CreateLicenseBadgeTest.php
- tests/Badge/Model/UseCase/CreateSuggestersBadgeTest.php
- tests/Badge/Model/UseCase/CreateVersionBadgeTest.php
- tests/Contributors/Service/RepositoryTest.php
- tests/EventListener/StatsSubscriberTest.php
- tests/Service/CircleCiClientTest.php
- yarn.lock
- Bump dependencies versions for client and server side.
- PhpCSFixer execute
> Bump dependencies versions

- .circleci/config.yml
- README.md
- composer.json
- composer.lock
- phpstan.neon
- src/Badge/Model/Badge.php
- src/Badge/Model/UseCase/CreateDependentsBadge.php
- src/Badge/Model/UseCase/CreateDownloadsBadge.php
- src/Badge/Model/UseCase/CreateGitAttributesBadge.php
- src/Badge/Model/UseCase/CreateSuggestersBadge.php
- src/Badge/Service/TextNormalizer.php
- src/Contributors/Command/UpdateCommand.php
- src/Contributors/Service/Repository.php
- src/EventListener/BadgeSubscriber.php
- src/Service/CachedClient.php
- symfony.lock
- tests/Badge/Model/ParseStabilityTest.php
- tests/Badge/Model/UseCase/CreateCircleCiBadgeTest.php
- tests/Badge/Model/UseCase/CreateComposerLockBadgeTest.php
- tests/Badge/Model/UseCase/CreateDependentsBadgeTest.php
- tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php
- tests/Badge/Model/UseCase/CreateLicenseBadgeTest.php
- tests/Badge/Model/UseCase/CreateSuggestersBadgeTest.php
- tests/Badge/Model/UseCase/CreateVersionBadgeTest.php
- tests/Badge/Service/TextNormalizerTest.php
- tests/Contributors/Service/RepositoryTest.php
- tests/EventListener/StatsSubscriberTest.php
- tests/Service/CircleCiClientTest.php
- tests/Service/SnippetGeneratorTest.php
Add phpstan and start to fix issues.
> [WIP] Add phpstan and start to fix issues

- .circleci/config.yml
- .env.test
- composer.json
- composer.lock
- config/services.yaml
- phpunit.xml.dist
- src/Badge/Model/UseCase/CreateCircleCiBadge.php
- src/Service/CircleCiClient.php
- src/Service/CircleCiClientInterface.php
- symfony.lock
- tests/Badge/Model/UseCase/CreateCircleCiBadgeTest.php
- tests/Service/CircleCiClientTest.php
[v3/bump-symfony-43 397efeb] Bump to Symfony 4.3
> Bump to Symfony 4.3

- .circleci/config.yml
- .env.dist
- .env.test
- composer.json
- composer.lock
- config/bundles.php
- config/packages/prod/sentry.yaml
- config/packages/sentry.yaml
- src/EventListener/BadgeSubscriber.php
- src/EventListener/StatsSubscriber.php
- symfony.lock
- tests/EventListener/StatsSubscriberTest.php
[feat/upgrade-sentry-and-phpunit adafc06] Upgrade sentry and phpunit
close #269
> Upgrade sentry and phpunit

- README.md
- composer.lock
- docker-compose.yml
- symfony.lock
- templates/home/index.html.twig
[v3/feat-update-dependecies 91fd5d3] feat: update symfony dependencies to 4.4.5 and twig 3.0
```
- Updating symfony/flex (v1.6.0 => v1.6.2): Loading from cache
- Updating symfony/service-contracts (v1.1.8 => v2.0.1): Loading from cache
- Updating symfony/polyfill-php73 (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/console (v4.4.2 => v4.4.5): Loading from cache
- Updating symfony/http-client-contracts (v1.1.8 => v2.0.1): Loading from cache
- Updating symfony/http-client (v4.4.2 => v4.4.5): Loading from cache
- Updating symfony/polyfill-ctype (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/polyfill-intl-idn (v1.13.1 => v1.14.0): Loading from cache
- Updating symfony/mime (v4.4.2 => …
```
> feat: update symfony dependencies to 4.4.5

- yarn.lock
[feat/upgrade-yarn-dependencies 614aa26] feat: upgrade yarn dependencies
I hope to fix alert! :D
> feat: upgrade yarn dependencies

- Makefile
- README.md
[feat/make-tool-build 41c43c2] Add make tool build
> Add make tool build

- composer.lock
[feat/update-dependencies-fix-security-alert 280aaa9] Update symfony dependencies and fix security alert: https://github.com/PUGX/badge-poser/network/alert/composer.lock/symfony%2Fhttp-foundation/open
```
- Updating symfony/asset (v4.4.5 => v4.4.7): Loading from cache
- Updating symfony/polyfill-mbstring (v1.14.0 => v1.15.0): Loading from cache
- Updating symfony/console (v4.4.5 => v4.4.7): Loading from cache
- Updating psr/log (1.1.2 => 1.1.3): Loading from cache
- Updating symfony/http-client (v4.4.5 => v4.4.7): Loading from cache
- Updating symfony/polyfill-ctype (v1.14.0 => v1.15.0): Loading from cache
- Updating symfony/yaml (v4.4.5 => v4.4.7): Loading from cache
- Updating symfony/dom-crawler (v4.4.5 => v4.4.7): Loading from cache
- Updating symfony/browser-kit (v4.4.5 => v4.4.7): …
```
> Update symfony dependencies and fix security alert

- src/EventListener/BadgeSubscriber.php
> 🐛 fix badge subscriber

- .circleci/config.yml
- composer.json
- composer.lock
- config/packages/sentry.yaml
[feat/upgrade-sentry ad4c05a] Upgrade Sentry to v3.5.1
closes #291
> Upgrade Sentry to v3.5.1

- src/Badge/Model/UseCase/CreateComposerLockBadge.php
[fixup/issues-295 08555d1] Fixup issue #295
> Fixup issue #295

- src/Badge/Model/UseCase/CreateGitAttributesBadge.php
[fixup/issue-301 3139059] Fixup issue close #301
> Fixup issue #301

- phpstan-baseline.neon
- src/Badge/Infrastructure/Package/PackageRepository.php
- src/Badge/Model/Badge.php
- src/Badge/Model/Image.php
- src/Badge/Model/Package.php
- tests/Contributors/Service/RepositoryTest.php
[fixup/php-cs-fixer 5b66a68] fix(cs): php-cs-fixer and stan
> fix(cs): php-cs-fixer and stan

- assets/js/app.js
- package.json
- yarn.lock
[feat/upgrade-sentry-sdk-js e67d207] feat(sentry): upgrade sdk js
> feat(sentry): upgrade sdk js

- assets/js/app.js
closes #172 
This might be enough to solve this specific issue.
That's far from ideal as we also need to take care of popping the state when pressing the back button, I'll work on that and come up with a PR (or update this one) soon
> Change url when selecting a package

- templates/base.html.twig
[fix/change-analytics-tracking fd16efb] fix: change analytics tracking
> fix: change analytics tracking

- .gitignore
- composer.json
- composer.lock
- symfony.lock
[chore/remove-composer-git-hooks 3123fa0] chore(hooks): Remove brainmaestro/composer-git-hooks
After merge, you must alignment with master and remove from your codebase:
```
rm .git/hooks/post-commit
rm .git/hooks/pre-commit
```
@garak @AlessandroMinoccheri @fabiocicerchia @Jean85 look at this please!
> chore(hooks): Remove brainmaestro/composer-git-hooks

- CONTRIBUTING.md
- Makefile
- README.md
[fix/improved-readme c98ad99] improved readme
> improved readme

- .circleci/config.yml
- .circleci/images/Dockerfile
- bin/console
I try to manage circle ci with workflows: https://circleci.com/docs/2.0/workflows/#workflows-configuration-examples
Not bad eh?
https://app.circleci.com/pipelines/github/PUGX/badge-poser/130/workflows/b699d9bd-540f-4c69-a14d-86c451025cd5
> Add CircleCI workflows

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BC_Break.md
- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Feature_Request.md
- .github/ISSUE_TEMPLATE/Support_Question.md
I think that it could be better to have a simple template for our issues.
What do you think?
> added issue template

- composer.json
- composer.lock
- src/Badge/Infrastructure/Package/PackageRepository.php
> ⬆️ update packagist-api. Fix #323

- .github/FUNDING.yml
[feat/add-github-sponsor-user 81f8c68] add github sponsor users
> add github sponsor users

- yarn.lock
This PR fixes an high priority security warning
See https://github.com/advisories/GHSA-hxcc-f52p-wc94
> 🔒 fix security issue with serialize-javascript

- composer.lock
See https://symfony.com/blog/cve-2020-15094-prevent-rce-when-calling-untrusted-remote-with-cachinghttpclient
> 🔒 fix security issue in Symfony

- .circleci/config.yml
- Makefile
- composer.json
- composer.lock
- docker-compose.yml
- phpstan-baseline.neon
- phpstan.neon
- phpunit.xml.dist
- yarn.lock
[fixup/stuff 77c1c10] fix of several things
> fix of several things

- composer.lock
[feat/upgrade-badges-poser d04031e] chore(deps): upgrade badges/poser to v2.0.4
> chore(deps): upgrade badges/poser to v2.0.4

- config/services.yaml
- phpstan-baseline.neon
- src/DateProvider/CurrentDateTimeProvider.php
- src/DateProvider/DateTimeProviderInterface.php
- src/Stats/Persister/NullPersister.php
- src/Stats/Persister/PersisterInterface.php
- src/Stats/Persister/RedisPersister.php
- tests/Stats/Persister/NullPersisterTest.php
- tests/Stats/Persister/RedisPersisterTest.php
- tests/Stats/Reader/NullReaderTest.php
- tests/Stats/Reader/RedisReaderTest.php
Please, look at code comments in order to take some decisions.
Is worty to note that I couldn't take advantage of dataProviders as `__construct` function (Redis one) don't accept `null` args for default values (I've left a comment in code in order to highlight this).
WDYT?
> Added tests for Stats

- .circleci/config.yml
- .gitignore
- README.md
See https://github.com/PUGX/badge-poser/issues/394
> Added code coverage report and badge

- src/Badge/Infrastructure/Package/PackageRepository.php
- src/Badge/Model/Package.php
- src/Badge/Model/UseCase/BaseCreatePackagistImage.php
- src/Badge/Model/UseCase/CreateCircleCiBadge.php
- src/Badge/Model/UseCase/CreateComposerLockBadge.php
- src/Badge/Model/UseCase/CreateDependentsBadge.php
- src/Badge/Model/UseCase/CreateDownloadsBadge.php
- src/Badge/Model/UseCase/CreateErrorBadge.php
- src/Badge/Model/UseCase/CreateGitAttributesBadge.php
- src/Badge/Model/UseCase/CreateLicenseBadge.php
- src/Badge/Model/UseCase/CreateSuggestersBadge.php
- src/Badge/Model/UseCase/CreateVersionBadge.php
- src/DateProvider/CurrentDateTimeProvider.php
- src/Service/SnippetGenerator.php
- tests/Badge/Model/UseCase/CreateErroreBadgeTest.php
- tests/Badge/Model/UseCase/CreateVersionBadgeTest.php
- tests/EventListener/BadgeSubscriberTest.php
- tests/EventListener/StatsSubscriberTest.php
- tests/Service/SnippetGeneratorTest.php
This is a draft PR.
Sneaking around, trying to improve test coverage.
I just stop for tests that's not unit tests, but other work can be done in order to cover more and more cases.
I left here for review. If good, as coverage is now more than 90% (that's a very good measure), we can directly merge it and open singular issues that can be picked by others.
WDYT?
> Test improvements: covered some possible execution path not yet tested

- CONTRIBUTING.md
- src/Badge/Model/UseCase/CreateVersionBadge.php
- sys/docker/alpine-phpfpm/Dockerfile
- sys/docker/alpine-phpfpm/start.sh
[fixup/dev-environment 08f3ecd] fix(env): dev environment
> fix(env): dev environment

- src/Controller/PackagistController.php
- tests/Controller/PackagistControllerTest.php
Fix #412 
A better solution would involve improving packagist-api searching.
A PR is currently waiting to be merged, see https://github.com/KnpLabs/packagist-api/pull/66
> limits packagist results

- src/Contributors/Model/Contributor.php
- templates/home/contributors.html.twig
- tests/Contributors/Model/ContributorTest.php
> make images of contributors smaller and lazy-loaded

- CONTRIBUTING.md
- Makefile
- docker-compose.yml
- sys/docker/alpine-nginx/Dockerfile
- sys/docker/alpine-phpfpm/Dockerfile
- sys/nginx/default.conf.template
- sys/php/php.ini-dev
[fix/improve-dev-environment 9923f65] Improved dev environment
> Improved dev environment

- composer.lock
- symfony.lock
- sys/docker/alpine-phpfpm/Dockerfile
[update-composer2-and-deps eddfee8] chore(deps): Update composer2 and dependecies
> chore(deps): Update composer2 and dependecies

- assets/js/app.js
- assets/js/elements-utils.js
hi,
it should fix "[Copy all badges](https://github.com/PUGX/badge-poser/issues/445)" issue
sorry i cant provide an automated test.
> UI bugfix.

- Makefile
- src/Contributors/Model/Contributor.php
- sys/cloudformation/parameters.prod.json
- sys/docker/alpine-nginx/Dockerfile
- sys/docker/alpine-nginx/expire.sh
- tests/Contributors/Model/ContributorTest.php
> Fix TTL cache issue

- docker-compose.yml
[fix/docker-compose-with-env-local d1a5e67] fix: docker-composer with env.local
> fix: docker-composer with env.local

- config/packages/dev/monolog.yaml
- config/packages/prod/monolog.yaml
- phpstan-baseline.neon
- src/Badge/Service/ImageFactory.php
- src/Event/BadgeEvent.php
- src/EventListener/BadgeLoggerSubscriber.php
- tests/Event/BadgeEventTest.php
- tests/EventListener/BadgeLoggerSubscriberTest.php
Example of log:
```
badge-poser-phpfpm | [2021-05-18T11:02:56.155152+00:00] badges.INFO: /phpunit/phpunit/v {"badgeData":{"subject":"stable","status":"9.5.4","color":"#28a3df","format":"svg"},"requestHeaders":{"cookie":["_ga=GA1.2.1221247998.1617793280; _gid=GA1.2.1449274797.1621268707"],"accept-language":["it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,es;q=0.5,fr;q=0.4,ru;q=0.3,da;q=0.2,pt;q=0.1"],"accept-encoding":["gzip, deflate"],"accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"user-agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"upgrade-insecure-requests":["1"],"cache-control":["no-cache"],"pragma":["n …
```
> feat: add logger to show badges

- .php-cs-fixer.dist.php
- yarn.lock
[feat/upgrade-dependencies-npm 93c6758] feat: upgrade dependencies npm
> feat: upgrade dependencies npm

- assets/styles/_input.scss
[fix/remove-x-onloading-spinner 527639e] fix: remove x onloading and spinner
> fix: remove x on-loading and spinner

- bin/console
- bin/phpunit
- composer.json
- composer.lock
- config/packages/framework.yaml
- config/routes/framework.yaml
- config/services.yaml
- public/index.php
- symfony.lock
- templates/home/index.html.twig
[feat/bump-sf-53 4afd179] feat: bump to symfony 5.3
- Bump to Symfony 5.3 and `--with-all-dependencies`
- Install [symfony/runtime](https://github.com/symfony/runtime)
- Update recipes
```
$ docker-compose exec phpfpm composer update --with-all-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.3.*"
Updating dependencies
Lock file operations: 2 installs, 41 updates, 0 removals
- Upgrading jean85/pretty-package-versions (2.0.3 => 2.0.4)
- Upgrading sentry/sentry (3.2.2 => 3.3.0)
- Upgrading sentry/sentry-symfony (4.1.2 => 4.1.3)
- Upgrading symfony/asset (v5.2.7 => v5.3.0)
- Upgrading symfony/browser-kit (v5.2.9 => v5.3.0)
- Upgrading symfony/cache (v5.2.9 => v5.3.0)
- Upgrading symfony/config (v5.2.8 => v5.3.0)
- …
```
> feat: bump to symfony 5.3

- composer.json
[feat/add-allow-packages-to-composer 0b6c00a] feat: add allow packages plugins to composer.json
> feat: add allow packages plugins to composer.json

- .env
- bin/phpunit
- composer.json
- composer.lock
- config/packages/routing.yaml
- config/packages/twig.yaml
- config/packages/webpack_encore.yaml
- phpunit.xml.dist
- src/Kernel.php
- symfony.lock
[feat/bump-sf-54 c0ca853] feat: bump to sf 5.4
```
- Upgrading symfony/flex (v1.17.2 => v1.17.6): Extracting archive
- Upgrading symfony/runtime (v5.3.10 => v5.4.1): Extracting archive
- Upgrading symfony/string (v5.3.10 => v5.4.0-RC1): Extracting archive
- Upgrading symfony/deprecation-contracts (v2.4.0 => v2.5.0): Extracting archive
- Upgrading symfony/service-contracts (v2.4.0 => v2.5.0): Extracting archive
- Upgrading symfony/console (v5.3.10 => v5.4.2): Extracting archive
- Upgrading symfony/http-client-contracts (v2.4.0 => v2.5.0): Extracting archive
- Upgrading symfony/http-client (v5.3.10 => v5.4.2): Extracting archive
- Upgrading symfony/options-resolver (v5.3.7 => v5.4.0): Extracting archive
- Upgrading php-http/client-common (2.4.0 => 2.5.0): Extracting archive
- Upgrading …
```
> feat: bump to sf 5.4

- package.json
[feat/add-volta-compatibility d39bc32] feat: add [volta](https://volta.sh/) compatibility
> feat: add volta compatibility

- .github/workflows/build.yml
- composer.lock
- phpstan.neon
- src/Badge/Model/Badge.php
- src/Badge/Model/Package.php
- src/Badge/Model/UseCase/CreateCircleCiBadge.php
In this Pull Request, I have updated all the dependencies and I have changed our Github Action using directly PHPStan instead of the specific action.
It seems that using the specific action has some problems.
I also launched the cs_fix in the project.
> updated dependencies

- .github/workflows/build.yml
- composer.json
- composer.lock
- phpunit.xml.dist
- src/Badge/Model/Package.php
- src/EventListener/BadgeLoggerSubscriber.php
- sys/docker/alpine-phpfpm/Dockerfile
- sys/php/docker-php-ext-opcache.ini
Also update php to 8.1 (otherwise we can't use Symfony 6.1)
> update php deps

- composer.json
- composer.lock
```
- Upgrading symfony/runtime (v6.1.3 => v6.2.0): Extracting archive
- Upgrading symfony/string (v6.2.0-RC1 => v6.2.0): Extracting archive
- Upgrading symfony/deprecation-contracts (v3.1.1 => v3.2.0): Extracting archive
- Upgrading symfony/console (v6.2.0-RC2 => v6.2.1): Extracting archive
- Upgrading symfony/http-client (v6.2.0-RC1 => v6.2.0): Extracting archive
- Upgrading symfony/options-resolver (v6.2.0-RC1 => v6.2.0): Extracting archive
- Upgrading composer/pcre (3.0.2 => 3.1.0): Extracting archive
- Installing doctrine/deprecations (v1.0.0): Extracting archive
- Upgrading doctrine/lexer (1.2.3 => 2.0.0): Extracting archive
- Upgrading symfony/stopwatch (v6.1.5 => v6.2.0): Extracting archive
- Upgrading symfony/process (v6.1.3 => v6.2.0): Extracting archive
- Upgrading …
```
> feat: bump to symfony 6.2

- assets/bootstrap.js
- config/packages/assets.yaml
- config/packages/prod/webpack_encore.yaml
- config/packages/test/webpack_encore.yaml
- config/packages/webpack_encore.yaml
- package.json
- symfony.lock
- webpack.config.js
- yarn.lock
Bump npm packages and @symfony/webpack-encore 4
> feat: bump npm packages

- composer.json
- composer.lock
Bump of all php deps to symfony 6.3.5
> feat: bump sf v6.3.5

- composer.json
- composer.lock
> remove unneeded ext-json requirement
